#Use R
language: r
cache:
  - packages
warnings_are_errors: false
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --ignore-vignettes"
dist: xenial
os: linux

r:
 - oldrel
 - release
 - devel

notifications:
  email:
    on_success: change
    on_failure: change
